// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Infrastructure.Database;

#nullable disable

namespace Notification.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notification")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notification.Domain.Models.NotificationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RecipientUserId", "ReadAt");

                    b.ToTable("Notifications", "notification");
                });

            modelBuilder.Entity("Notification.Domain.Models.NotificationItem", b =>
                {
                    b.OwnsOne("Notification.Domain.ValueObjects.DeepLink", "Link", b1 =>
                        {
                            b1.Property<Guid>("NotificationItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)")
                                .HasColumnName("DeepLink");

                            b1.HasKey("NotificationItemId");

                            b1.ToTable("Notifications", "notification");

                            b1.WithOwner()
                                .HasForeignKey("NotificationItemId");
                        });

                    b.OwnsOne("Notification.Domain.ValueObjects.NotificationMessage", "Message", b1 =>
                        {
                            b1.Property<Guid>("NotificationItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("NotificationItemId");

                            b1.ToTable("Notifications", "notification");

                            b1.WithOwner()
                                .HasForeignKey("NotificationItemId");
                        });

                    b.Navigation("Link")
                        .IsRequired();

                    b.Navigation("Message")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
